### ISSUE TITLE
Step 4.4 Doesn't save when deleted

### ISSUE THREAD

**Issue by grantkemp** [udacity/ios-persistence#1]
Step 4.4 does not persist deletions   -> Looks like there is no save in the method

    override func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
        if editingStyle == .Delete {
            objects.removeAtIndex(indexPath.row)
            tableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: .Fade)
        } else if editingStyle == .Insert {
            // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view.
        }
    }

**Comment by grantkemp** [comment]
I added a Pull request with a fix that worked for me. Hope this helps others.

**Comment by ccrazy88** [comment]
For further reference: https://github.com/udacity/ios-persistence/pull/3
